name: slate
description: "Slate Backend - SMB remote album with local album support"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  mime: ^1.0.5
  path: ^1.9.0
  crypto: ^3.0.3

dev_dependencies:
  lints: ^5.0.0
